### ISSUE TITLE
Update or remove GitHub pages website

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#190]
## What problem does this solve or what need does it fill?

Apparently we have a GitHub pages website at <https://dioxuslabs.github.io/taffy/>.
It uses all the old logos, names and code examples from Stretch and is therefore very out of date.

## What solution would you like?

Either (a) update all names, descriptions and code examples on the website or (b) remove it entirely (for now).

## What alternative(s) have you considered?

N/A

## Additional context

I found the website through the Environments section on the repository:
![Environment section of the repository](https://user-images.githubusercontent.com/13908946/175770590-f212318c-0e5a-42ce-ab14-dfbe83e8be63.png)

Note that this section can also be hidden in the repo settings.

The code of the website resides on the [`gh-pages` branch](https://github.com/DioxusLabs/taffy/tree/gh-pages), but it seems to be compiled from some other source? No idea where that is coming from.

**Comment by alice-i-cecile** [comment]
Ping @jkelleyrtp; I suspect you may know more.

**Comment by mockersf** [comment]
The `gh-pages` branch comes from stretch and has not been updated since. It should probably be deleted

**Comment by alice-i-cecile** [comment]
Done! I've deleted all of the stale branches.

**Comment by TimJentzsch** [comment]
The environment is still showing on the repository page, it should probably be hidden or unlinked (if possible).

**Comment by alice-i-cecile** [comment]
Environment hidden! And Github Pages should be disabled now.

![image](https://user-images.githubusercontent.com/3579909/175778665-5fda171b-32ae-413d-8f82-b46db2be74bd.png)
