### ISSUE TITLE
Retained max size in flex layout

### ISSUE THREAD

**Issue by jrmoulton** [DioxusLabs/taffy#480]
## `taffy` version

0.3.12

## Platform

Rust, MacOS / Windows in the floem GUI framework

## What you did

I'm having a hard time tracking down the source of the bug but I'm fairly confident that the issue is inside of taffy. 

I have a flex layout (flex row) that has 3 items with the last being set to flex grow (1.0). The item properly flexes and grows when the view width is increased but it then retains it's largest size and the item that is set to flex grow doesn't shrink when the view is decreased in width. 

## Additional information

I'm guessing that somewhere in the computation of the size of the flex layout a maximum size is being retained. 

https://github.com/DioxusLabs/taffy/assets/13090441/dbbff894-1f6e-40b2-8849-580ce57d0edf

**Comment by nicoburns** [comment]
Hmm... This likely is a bug in Taffy. However before we really dig into this can you double check that you're actually running `v0.3.12` (check your `Cargo.lock` file and perhaps run `cargo update` for good measure)? We already fixed a similar bug in the `v0.3.9` release, so this would be a known (and fixed) issue if you're running a version that's older than that.

Beyond that, do you have a runnable example that exhibits the problem? Ideally in a reduced form that just uses Taffy (something like these tests perhaps https://github.com/DioxusLabs/taffy/blob/main/tests/relayout.rs#L278), but even a runnable branch of Lapce (where you could point out the problematic part of the code) would be better than nothing.

The caching logic in https://github.com/DioxusLabs/taffy/blob/main/src/tree/cache.rs is likely the culprit if you want to look into this yourself. Just changing the `get` function to always return `None` would be a good way to test that (but will make layout really slow!). (but I certainly don't expect you to look into this yourself)

**Comment by jrmoulton** [comment]
An update on this issue.

Ran cargo update, checked the lock file and confirmed version 0.3.12 is being used. I am also using a local version of taffy checked out at the v0.3.12 tag. The problem still remains. 

I updated the get function in the caching logic to always return None but the error remains. 

I'll work on getting a reproducible example

**Comment by nicoburns** [comment]
Hmm... odd that bypassing the cache doesn't fix things. That makes me think that the issue might *not* be in Taffy. As that's really the only place we persist data between layout runs (also in the output `Layout` structs, but those should all get overwritten if the cache returns None).

**Comment by jrmoulton** [comment]
Interesting Ok. Well I'll probably be a few months before I circle back to this issue so since it's probably not in taffy I'll close it for now and reopen it in the future if the problem persists and it still seems to be in taffy. Thanks!
